### PR TITLE
Add python3-lxml to CentOS 8 and RedHat 8

### PR DESCRIPTION
**Pull request by DavidDessertine**
---
name: Pull request
about: Describe the proposed change

---

**Describe the change**
I see CentOS8 / RHEL8 needs python3-lxml.

### CODE REVIEW

**Comment by robertdebock** [comment]
Looks like CI is going to pass.

What was failing before adding `python3-lxml`? I would like to write a test for that too. (You're allowed to do that as well, in `molecule/default/verify.yml`.)

Thanks for the help @Climberdav

**Comment by robertdebock** [comment]
I think the `xml` module requires this change, correct?

Supporting the `xml` module is not the goal of this role, this goal is "just" to make a system ready to be managed by Ansible.

May I suggest using the [software](https://galaxy.ansible.com/robertdebock/software) role to install other software? Something like this:

```yaml
  roles:
    - role: robertdebock.bootstrap
    - role: robertdebock.software
      software_packages:
        - name: python3-lxml
```

(Or save the variable `software_packages` in another location such as `group_vars`.

I'll leave the issue open for a bit, allowing you to respond. Once again, thanks for the help!

**Comment by DavidDessertine** [comment]
Hi,
It's used to perform downloads from the web. For exemple in my main playbook I need to download mysql-connector from maven. And it fails : `Failed to import the required Python library (lxml) on centos-8's Python /usr/libexec/platform-python`

I apologies, I didn't use your software role.

I just tried it work on centos8 but not on centos7.

I try to create a tomcat role (corresponding to my needs, I have to personalize web.xml, setenv.sh, server.xml and context.xml

Regards

**Comment by DavidDessertine** [comment]
Ok so using this it's OK :
```yml
  roles:
    - role: robertdebock.bootstrap
    - role: robertdebock.software
      software_packages:
        - name: python3-lxml
      when: ansible_os_family in ['RedHat', 'CentOS'] and ansible_distribution_major_version == "8"
    - role: robertdebock.software
      software_packages:
        - name: python-lxml
      when: ansible_os_family in ['RedHat', 'CentOS'] and ansible_distribution_major_version == "7"
    - role: robertdebock.java
      java_type: jdk
      java_version: 13
```
So PR is not necessary
Regards

**Comment by robertdebock** [comment]
Thanks for replying, I'll close the PR.

**Pull request closed without merging**
